version: '3.8'

services:
  productboard-db:
    image: postgres:14-alpine
    container_name: productboard-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: productboard
      POSTGRES_USER: vojta
      POSTGRES_PASSWORD: vojta
    volumes:
      - productboard-db-data:/var/lib/postgresql/data

volumes:
  productboard-db-data:
